import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  FolderOpen, FileCode2, FileText, File, Download,
  Trash2, ChevronRight, Inbox, ExternalLink, Archive,
} from "lucide-react";
import { toast } from "sonner";
import JSZip from "jszip";
import { Link } from "wouter";

const WS_KEY = "xdx_workspace_v6";

type GeneratedFile = { name: string; content: string; language: string };
type BuildRecord   = { id: string; prompt: string; mode: string; files: GeneratedFile[]; builtAt: string; version: number };

function getFileIcon(name: string) {
  const ext = name.split(".").pop()?.toLowerCase() ?? "";
  if (["js","ts","tsx","jsx","py","php","go","dart","rs","rb"].includes(ext)) return FileCode2;
  if (["md","txt","yml","yaml","json","env","toml","sql"].includes(ext))        return FileText;
  return File;
}

function sizeLabel(content: string): string {
  const bytes = new TextEncoder().encode(content).length;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function totalSize(files: GeneratedFile[]): string {
  const bytes = files.reduce((s, f) => s + new TextEncoder().encode(f.content).length, 0);
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

async function downloadZip(files: GeneratedFile[], name: string) {
  const zip = new JSZip();
  const folder = zip.folder(name.replace(/[^a-z0-9-_]/gi, "-").slice(0, 40) || "project")!;
  files.forEach(f => folder.file(f.name, f.content));
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${name.slice(0, 30).replace(/[^a-z0-9]/gi, "-")}.zip`;
  a.click(); URL.revokeObjectURL(a.href);
  toast.success("ZIP downloaded!");
}

function downloadFile(f: GeneratedFile) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([f.content], { type: "text/plain" }));
  a.download = f.name.split("/").pop() ?? f.name;
  a.click(); URL.revokeObjectURL(a.href);
}

export default function FilesPage() {
  const [history, setHistory] = useState<BuildRecord[]>([]);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  useEffect(() => {
    try {
      const raw = localStorage.getItem(WS_KEY);
      if (!raw) return;
      const ws = JSON.parse(raw);
      const builds: BuildRecord[] = ws.buildHistory ?? [];
      setHistory(builds);
      if (builds.length) setExpanded(new Set([builds[0]!.id]));
    } catch { /* empty workspace */ }
  }, []);

  const toggleBuild = (id: string) =>
    setExpanded(prev => { const n = new Set(prev); n.has(id) ? n.delete(id) : n.add(id); return n; });

  const totalFiles = history.reduce((s, b) => s + b.files.length, 0);
  const totalBytes = history.reduce((s, b) =>
    s + b.files.reduce((ss, f) => ss + new TextEncoder().encode(f.content).length, 0), 0);
  const totalBytesLabel = totalBytes < 1024 ? `${totalBytes} B`
    : totalBytes < 1024 * 1024 ? `${(totalBytes / 1024).toFixed(1)} KB`
    : `${(totalBytes / (1024 * 1024)).toFixed(2)} MB`;

  if (history.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4 text-center">
        <Inbox className="w-16 h-16 text-muted-foreground/20" />
        <h2 className="text-xl font-semibold">No builds yet</h2>
        <p className="text-sm text-muted-foreground max-w-sm">
          Files you build in the AI Workspace will appear here automatically — ready to browse, download, or ZIP.
        </p>
        <Link href="/workspace">
          <Button className="gap-2 mt-2"><ExternalLink className="w-4 h-4" /> Go to AI Workspace</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Files</h1>
          <p className="text-sm text-muted-foreground mt-1">All files generated by the AI Workspace</p>
        </div>
        <Link href="/workspace">
          <Button variant="outline" size="sm" className="gap-1.5 text-xs">
            <ExternalLink className="w-3.5 h-3.5" /> Open Workspace
          </Button>
        </Link>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: "Total Files",  value: totalFiles.toString(),      icon: FileCode2, color: "text-blue-400" },
          { label: "Total Size",   value: totalBytesLabel,             icon: Archive,   color: "text-green-400" },
          { label: "Build Runs",   value: history.length.toString(),   icon: FolderOpen, color: "text-amber-400" },
        ].map(s => (
          <Card key={s.label} className="bg-card/50 border-border/50">
            <CardContent className="flex items-center gap-3 p-4">
              <s.icon className={`w-8 h-8 ${s.color} opacity-80`} />
              <div>
                <div className="text-xl font-bold">{s.value}</div>
                <div className="text-xs text-muted-foreground">{s.label}</div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Build list */}
      <div className="space-y-3">
        {history.map(build => {
          const isOpen = expanded.has(build.id);
          return (
            <Card key={build.id} className="bg-card/50 border-border/50 overflow-hidden">
              {/* Header row */}
              <button
                className="w-full flex items-center gap-3 p-4 hover:bg-muted/20 transition-colors text-left"
                onClick={() => toggleBuild(build.id)}
              >
                <ChevronRight className={`w-4 h-4 text-muted-foreground shrink-0 transition-transform ${isOpen ? "rotate-90" : ""}`} />
                <FolderOpen className="w-4 h-4 text-amber-400 shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-sm truncate">{build.prompt}</p>
                  <p className="text-[11px] text-muted-foreground">{build.builtAt} · {build.files.length} files · {totalSize(build.files)}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <Badge variant="outline" className="text-[10px] font-mono">v{build.version}</Badge>
                  <Badge variant="secondary" className="text-[10px]">{build.mode}</Badge>
                  <Button size="sm" variant="outline" className="gap-1 text-xs h-7"
                    onClick={e => { e.stopPropagation(); downloadZip(build.files, build.prompt); }}>
                    <Download className="w-3 h-3" /> ZIP
                  </Button>
                </div>
              </button>

              {/* File list */}
              {isOpen && (
                <div className="border-t border-border/30">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border/20 bg-muted/10">
                        <th className="text-left text-[11px] font-medium text-muted-foreground px-4 py-2">File</th>
                        <th className="text-left text-[11px] font-medium text-muted-foreground px-4 py-2 hidden sm:table-cell">Language</th>
                        <th className="text-left text-[11px] font-medium text-muted-foreground px-4 py-2 hidden sm:table-cell">Size</th>
                        <th className="px-4 py-2 w-16" />
                      </tr>
                    </thead>
                    <tbody>
                      {build.files.map(f => {
                        const Icon = getFileIcon(f.name);
                        return (
                          <tr key={f.name} className="border-b border-border/10 last:border-0 hover:bg-muted/10 transition-colors">
                            <td className="px-4 py-2.5">
                              <div className="flex items-center gap-2">
                                <Icon className="w-4 h-4 text-blue-400 shrink-0" />
                                <span className="font-mono text-xs truncate max-w-[160px] sm:max-w-none">{f.name}</span>
                              </div>
                            </td>
                            <td className="px-4 py-2.5 text-muted-foreground text-xs hidden sm:table-cell">{f.language}</td>
                            <td className="px-4 py-2.5 text-muted-foreground text-xs hidden sm:table-cell">{sizeLabel(f.content)}</td>
                            <td className="px-4 py-2.5">
                              <div className="flex items-center gap-1 justify-end">
                                <Button size="icon" variant="ghost" className="h-6 w-6 text-muted-foreground hover:text-foreground"
                                  onClick={() => downloadFile(f)}>
                                  <Download className="w-3 h-3" />
                                </Button>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </Card>
          );
        })}
      </div>
    </div>
  );
}
