import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  FolderOpen, FileCode2, FileText, File, Plus, Upload,
  FolderPlus, RefreshCw, Download, Trash2, ChevronRight,
} from "lucide-react";

type FileNode = {
  name: string;
  type: "file" | "folder";
  size?: string;
  modified?: string;
  children?: FileNode[];
};

const DEMO_FILES: FileNode[] = [
  {
    name: "my-saas-app",
    type: "folder",
    children: [
      {
        name: "frontend",
        type: "folder",
        children: [
          { name: "index.html", type: "file", size: "4.2 KB", modified: "2 min ago" },
          { name: "styles.css", type: "file", size: "1.8 KB", modified: "2 min ago" },
          { name: "app.js", type: "file", size: "3.1 KB", modified: "2 min ago" },
        ],
      },
      {
        name: "backend",
        type: "folder",
        children: [
          { name: "server.py", type: "file", size: "2.4 KB", modified: "5 min ago" },
          { name: "requirements.txt", type: "file", size: "312 B", modified: "5 min ago" },
        ],
      },
      { name: "README.md", type: "file", size: "1.1 KB", modified: "5 min ago" },
      { name: "docker-compose.yml", type: "file", size: "780 B", modified: "5 min ago" },
    ],
  },
  {
    name: "telegram-bot",
    type: "folder",
    children: [
      { name: "bot.py", type: "file", size: "5.6 KB", modified: "1 hour ago" },
      { name: "handlers.py", type: "file", size: "3.2 KB", modified: "1 hour ago" },
      { name: ".env.example", type: "file", size: "148 B", modified: "1 hour ago" },
    ],
  },
  { name: "deployment-notes.md", type: "file", size: "2.3 KB", modified: "Yesterday" },
];

function getFileIcon(node: FileNode) {
  if (node.type === "folder") return FolderOpen;
  const ext = node.name.split(".").pop()?.toLowerCase();
  if (["js", "ts", "tsx", "jsx", "py", "php", "go", "dart"].includes(ext ?? "")) return FileCode2;
  if (["md", "txt", "yml", "yaml", "json", "env"].includes(ext ?? "")) return FileText;
  return File;
}

function FileTree({ nodes, depth = 0 }: { nodes: FileNode[]; depth?: number }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set(["my-saas-app", "frontend"]));

  return (
    <div>
      {nodes.map(node => {
        const Icon = getFileIcon(node);
        const isExpanded = expanded.has(node.name);
        return (
          <div key={node.name}>
            <div
              className="flex items-center gap-2 px-3 py-1.5 hover:bg-muted/40 cursor-pointer rounded-md group text-sm"
              style={{ paddingLeft: `${12 + depth * 16}px` }}
              onClick={() => {
                if (node.type === "folder") {
                  setExpanded(prev => {
                    const next = new Set(prev);
                    next.has(node.name) ? next.delete(node.name) : next.add(node.name);
                    return next;
                  });
                }
              }}
            >
              {node.type === "folder" && (
                <ChevronRight className={`w-3 h-3 text-muted-foreground transition-transform ${isExpanded ? "rotate-90" : ""}`} />
              )}
              {node.type === "file" && <span className="w-3" />}
              <Icon className={`w-4 h-4 shrink-0 ${node.type === "folder" ? "text-amber-400" : "text-blue-400"}`} />
              <span className="flex-1 truncate">{node.name}</span>
              {node.size && <span className="text-[11px] text-muted-foreground opacity-0 group-hover:opacity-100">{node.size}</span>}
            </div>
            {node.type === "folder" && isExpanded && node.children && (
              <FileTree nodes={node.children} depth={depth + 1} />
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function FilesPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Files</h1>
          <p className="text-sm text-muted-foreground mt-1">Browse and manage all project files generated by AI</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-1.5 text-xs"><Upload className="w-3.5 h-3.5" /> Upload</Button>
          <Button variant="outline" size="sm" className="gap-1.5 text-xs"><FolderPlus className="w-3.5 h-3.5" /> New Folder</Button>
          <Button size="sm" className="gap-1.5 text-xs"><Plus className="w-3.5 h-3.5" /> New File</Button>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-6">
        {/* File tree */}
        <div className="col-span-1">
          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-2">
              <div className="flex items-center justify-between px-3 py-2 border-b border-border/50 mb-1">
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Explorer</span>
                <button className="text-muted-foreground hover:text-foreground"><RefreshCw className="w-3 h-3" /></button>
              </div>
              <FileTree nodes={DEMO_FILES} />
            </CardContent>
          </Card>
        </div>

        {/* Main content */}
        <div className="col-span-3 space-y-4">
          <div className="grid grid-cols-3 gap-3">
            {[
              { label: "Total Files", value: "12", icon: FileCode2, color: "text-blue-400" },
              { label: "Total Size", value: "24.8 KB", icon: File, color: "text-green-400" },
              { label: "Projects", value: "2", icon: FolderOpen, color: "text-amber-400" },
            ].map(s => (
              <Card key={s.label} className="bg-card/50 border-border/50">
                <CardContent className="flex items-center gap-3 p-4">
                  <s.icon className={`w-8 h-8 ${s.color} opacity-80`} />
                  <div>
                    <div className="text-xl font-bold">{s.value}</div>
                    <div className="text-xs text-muted-foreground">{s.label}</div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="bg-card/50 border-border/50">
            <CardContent className="p-0">
              <div className="flex items-center gap-3 px-4 py-3 border-b border-border/50">
                <span className="text-sm font-semibold">Recent Files</span>
                <Badge variant="outline" className="text-[10px]">12 files</Badge>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border/30">
                    <th className="text-left text-xs font-medium text-muted-foreground px-4 py-2">Name</th>
                    <th className="text-left text-xs font-medium text-muted-foreground px-4 py-2">Size</th>
                    <th className="text-left text-xs font-medium text-muted-foreground px-4 py-2">Modified</th>
                    <th className="px-4 py-2" />
                  </tr>
                </thead>
                <tbody>
                  {[
                    { name: "index.html", folder: "my-saas-app/frontend", size: "4.2 KB", modified: "2 min ago" },
                    { name: "server.py", folder: "my-saas-app/backend", size: "2.4 KB", modified: "5 min ago" },
                    { name: "bot.py", folder: "telegram-bot", size: "5.6 KB", modified: "1 hour ago" },
                    { name: "docker-compose.yml", folder: "my-saas-app", size: "780 B", modified: "5 min ago" },
                    { name: "README.md", folder: "my-saas-app", size: "1.1 KB", modified: "5 min ago" },
                  ].map(f => (
                    <tr key={f.name} className="border-b border-border/20 hover:bg-muted/20 transition-colors">
                      <td className="px-4 py-2.5">
                        <div className="flex items-center gap-2">
                          <FileCode2 className="w-4 h-4 text-blue-400 shrink-0" />
                          <div>
                            <div className="font-medium">{f.name}</div>
                            <div className="text-[11px] text-muted-foreground">{f.folder}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-2.5 text-muted-foreground text-xs">{f.size}</td>
                      <td className="px-4 py-2.5 text-muted-foreground text-xs">{f.modified}</td>
                      <td className="px-4 py-2.5">
                        <div className="flex items-center gap-1 justify-end">
                          <Button size="icon" variant="ghost" className="h-6 w-6 text-muted-foreground"><Download className="w-3 h-3" /></Button>
                          <Button size="icon" variant="ghost" className="h-6 w-6 text-muted-foreground hover:text-red-400"><Trash2 className="w-3 h-3" /></Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
